/* This file is automatically generated.  Do not edit. */
#ifndef _SELINUX_FLASK_H_
#define _SELINUX_FLASK_H_

#if defined(__XEN__) || defined(__XEN_TOOLS__)

/*
 * Security object class definitions
 */

/*
 * Security identifier indices for initial entities
 */
#define SECINITSID_XEN                                  1
#define SECINITSID_DOM0                                 2
#define SECINITSID_DOMIO                                3
#define SECINITSID_DOMXEN                               4
#define SECINITSID_UNLABELED                            5
#define SECINITSID_SECURITY                             6
#define SECINITSID_IOPORT                               7
#define SECINITSID_IOMEM                                8
#define SECINITSID_IRQ                                  9
#define SECINITSID_DEVICE                               10
#define SECINITSID_DOMU                                 11
#define SECINITSID_DOMDM                                12

#define SECINITSID_NUM                                  12

#endif /* __XEN__ || __XEN_TOOLS__ */

#endif
