
/* DO NOT EDIT.
 *
 * This file is autogenerated by
 * "gentypes.py libxl_types_internal.idl __libxl_types_internal.h __libxl_types_internal_private.h __libxl_types_internal_json.h __libxl_types_internal.c"
 */

#include "libxl_osdeps.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "libxl_internal.h"


void libxl__device_console_dispose(libxl__device_console *p)
{
    if (!p) return;
    free(p->output);
    free(p->name);
    free(p->connection);
    free(p->path);
    memset(p, 0, sizeof(*p));
}

void libxl__device_console_copy(libxl_ctx *ctx, libxl__device_console *dst, libxl__device_console *src)
{
    GC_INIT(ctx);
    dst->backend_domid = src->backend_domid;
    dst->devid = src->devid;
    dst->consback = src->consback;
    libxl_string_copy(ctx, &dst->output, &src->output);
    libxl_string_copy(ctx, &dst->name, &src->name);
    libxl_string_copy(ctx, &dst->connection, &src->connection);
    libxl_string_copy(ctx, &dst->path, &src->path);
    GC_FREE;
}

void libxl__device_console_init(libxl__device_console *p)
{
    memset(p, '\0', sizeof(*p));
}

const char *libxl__qmp_message_type_to_string(libxl__qmp_message_type e)
{
    switch(e) {
        case LIBXL__QMP_MESSAGE_TYPE_QMP:
            return "qmp";
        case LIBXL__QMP_MESSAGE_TYPE_RETURN:
            return "return";
        case LIBXL__QMP_MESSAGE_TYPE_ERROR:
            return "error";
        case LIBXL__QMP_MESSAGE_TYPE_EVENT:
            return "event";
        case LIBXL__QMP_MESSAGE_TYPE_INVALID:
            return "invalid";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__qmp_message_type_string_table[] = {
    { .s = "qmp", .v = LIBXL__QMP_MESSAGE_TYPE_QMP },
    { .s = "return", .v = LIBXL__QMP_MESSAGE_TYPE_RETURN },
    { .s = "error", .v = LIBXL__QMP_MESSAGE_TYPE_ERROR },
    { .s = "event", .v = LIBXL__QMP_MESSAGE_TYPE_EVENT },
    { .s = "invalid", .v = LIBXL__QMP_MESSAGE_TYPE_INVALID },
    { NULL, -1 },
};

int libxl__qmp_message_type_from_string(const char *s, libxl__qmp_message_type *e)
{
    return libxl__enum_from_string(libxl__qmp_message_type_string_table,
                                   s, (int *)e);
}

const char *libxl__device_kind_to_string(libxl__device_kind e)
{
    switch(e) {
        case LIBXL__DEVICE_KIND_VIF:
            return "vif";
        case LIBXL__DEVICE_KIND_VBD:
            return "vbd";
        case LIBXL__DEVICE_KIND_QDISK:
            return "qdisk";
        case LIBXL__DEVICE_KIND_PCI:
            return "pci";
        case LIBXL__DEVICE_KIND_VFB:
            return "vfb";
        case LIBXL__DEVICE_KIND_VKBD:
            return "vkbd";
        case LIBXL__DEVICE_KIND_CONSOLE:
            return "console";
        case LIBXL__DEVICE_KIND_VTPM:
            return "vtpm";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__device_kind_string_table[] = {
    { .s = "vif", .v = LIBXL__DEVICE_KIND_VIF },
    { .s = "vbd", .v = LIBXL__DEVICE_KIND_VBD },
    { .s = "qdisk", .v = LIBXL__DEVICE_KIND_QDISK },
    { .s = "pci", .v = LIBXL__DEVICE_KIND_PCI },
    { .s = "vfb", .v = LIBXL__DEVICE_KIND_VFB },
    { .s = "vkbd", .v = LIBXL__DEVICE_KIND_VKBD },
    { .s = "console", .v = LIBXL__DEVICE_KIND_CONSOLE },
    { .s = "vtpm", .v = LIBXL__DEVICE_KIND_VTPM },
    { NULL, -1 },
};

int libxl__device_kind_from_string(const char *s, libxl__device_kind *e)
{
    return libxl__enum_from_string(libxl__device_kind_string_table,
                                   s, (int *)e);
}

const char *libxl__console_backend_to_string(libxl__console_backend e)
{
    switch(e) {
        case LIBXL__CONSOLE_BACKEND_XENCONSOLED:
            return "xenconsoled";
        case LIBXL__CONSOLE_BACKEND_IOEMU:
            return "ioemu";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__console_backend_string_table[] = {
    { .s = "xenconsoled", .v = LIBXL__CONSOLE_BACKEND_XENCONSOLED },
    { .s = "ioemu", .v = LIBXL__CONSOLE_BACKEND_IOEMU },
    { NULL, -1 },
};

int libxl__console_backend_from_string(const char *s, libxl__console_backend *e)
{
    return libxl__enum_from_string(libxl__console_backend_string_table,
                                   s, (int *)e);
}

const char *libxl__device_action_to_string(libxl__device_action e)
{
    switch(e) {
        case LIBXL__DEVICE_ACTION_ADD:
            return "add";
        case LIBXL__DEVICE_ACTION_REMOVE:
            return "remove";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__device_action_string_table[] = {
    { .s = "add", .v = LIBXL__DEVICE_ACTION_ADD },
    { .s = "remove", .v = LIBXL__DEVICE_ACTION_REMOVE },
    { NULL, -1 },
};

int libxl__device_action_from_string(const char *s, libxl__device_action *e)
{
    return libxl__enum_from_string(libxl__device_action_string_table,
                                   s, (int *)e);
}

yajl_gen_status libxl__qmp_message_type_gen_json(yajl_gen hand, libxl__qmp_message_type *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__qmp_message_type_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__qmp_message_type_to_json(libxl_ctx *ctx, libxl__qmp_message_type p)
{
    return libxl__object_to_json(ctx, "libxl__qmp_message_type", (libxl__gen_json_callback)&libxl__qmp_message_type_gen_json, (void *)&p);
}

yajl_gen_status libxl__device_kind_gen_json(yajl_gen hand, libxl__device_kind *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__device_kind_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__device_kind_to_json(libxl_ctx *ctx, libxl__device_kind p)
{
    return libxl__object_to_json(ctx, "libxl__device_kind", (libxl__gen_json_callback)&libxl__device_kind_gen_json, (void *)&p);
}

yajl_gen_status libxl__console_backend_gen_json(yajl_gen hand, libxl__console_backend *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__console_backend_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__console_backend_to_json(libxl_ctx *ctx, libxl__console_backend p)
{
    return libxl__object_to_json(ctx, "libxl__console_backend", (libxl__gen_json_callback)&libxl__console_backend_gen_json, (void *)&p);
}

yajl_gen_status libxl__device_console_gen_json(yajl_gen hand, libxl__device_console *p)
{
    yajl_gen_status s;
    s = yajl_gen_map_open(hand);
    if (s != yajl_gen_status_ok)
        goto out;
    if (p->backend_domid) {
        s = yajl_gen_string(hand, (const unsigned char *)"backend_domid", sizeof("backend_domid")-1);
        if (s != yajl_gen_status_ok)
            goto out;
        s = yajl_gen_integer(hand, p->backend_domid);
        if (s != yajl_gen_status_ok)
            goto out;
    }
    if (p->devid) {
        s = yajl_gen_string(hand, (const unsigned char *)"devid", sizeof("devid")-1);
        if (s != yajl_gen_status_ok)
            goto out;
        s = yajl_gen_integer(hand, p->devid);
        if (s != yajl_gen_status_ok)
            goto out;
    }
    if (p->consback) {
        s = yajl_gen_string(hand, (const unsigned char *)"consback", sizeof("consback")-1);
        if (s != yajl_gen_status_ok)
            goto out;
        s = libxl__yajl_gen_enum(hand, libxl__console_backend_to_string(p->consback));
        if (s != yajl_gen_status_ok)
            goto out;
    }
    if (p->output) {
        s = yajl_gen_string(hand, (const unsigned char *)"output", sizeof("output")-1);
        if (s != yajl_gen_status_ok)
            goto out;
        s = libxl__string_gen_json(hand, p->output);
        if (s != yajl_gen_status_ok)
            goto out;
    }
    if (p->name) {
        s = yajl_gen_string(hand, (const unsigned char *)"name", sizeof("name")-1);
        if (s != yajl_gen_status_ok)
            goto out;
        s = libxl__string_gen_json(hand, p->name);
        if (s != yajl_gen_status_ok)
            goto out;
    }
    if (p->connection) {
        s = yajl_gen_string(hand, (const unsigned char *)"connection", sizeof("connection")-1);
        if (s != yajl_gen_status_ok)
            goto out;
        s = libxl__string_gen_json(hand, p->connection);
        if (s != yajl_gen_status_ok)
            goto out;
    }
    if (p->path) {
        s = yajl_gen_string(hand, (const unsigned char *)"path", sizeof("path")-1);
        if (s != yajl_gen_status_ok)
            goto out;
        s = libxl__string_gen_json(hand, p->path);
        if (s != yajl_gen_status_ok)
            goto out;
    }
    s = yajl_gen_map_close(hand);
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__device_console_to_json(libxl_ctx *ctx, libxl__device_console *p)
{
    return libxl__object_to_json(ctx, "libxl__device_console", (libxl__gen_json_callback)&libxl__device_console_gen_json, (void *)p);
}

yajl_gen_status libxl__device_action_gen_json(yajl_gen hand, libxl__device_action *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__device_action_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__device_action_to_json(libxl_ctx *ctx, libxl__device_action p)
{
    return libxl__object_to_json(ctx, "libxl__device_action", (libxl__gen_json_callback)&libxl__device_action_gen_json, (void *)&p);
}

int libxl___qmp_message_type_parse_json(libxl__gc *gc, const libxl__json_object *o, libxl__qmp_message_type *p)
{
    int rc = 0;
    const libxl__json_object *x = o;
    {
        const char *enum_str;
        if (!libxl__json_object_is_string(x)) {
            rc = -1;
            goto out;
        }
        enum_str = libxl__json_object_get_string(x);
        rc = libxl__qmp_message_type_from_string(enum_str, p);
        if (rc)
            goto out;
    }
    out:
    return rc;
}

int libxl__qmp_message_type_from_json(libxl_ctx *ctx, libxl__qmp_message_type *p, const char *s)
{
    return libxl__object_from_json(ctx, "libxl__qmp_message_type", (libxl__json_parse_callback)&libxl___qmp_message_type_parse_json, p, s);
}

int libxl___device_kind_parse_json(libxl__gc *gc, const libxl__json_object *o, libxl__device_kind *p)
{
    int rc = 0;
    const libxl__json_object *x = o;
    {
        const char *enum_str;
        if (!libxl__json_object_is_string(x)) {
            rc = -1;
            goto out;
        }
        enum_str = libxl__json_object_get_string(x);
        rc = libxl__device_kind_from_string(enum_str, p);
        if (rc)
            goto out;
    }
    out:
    return rc;
}

int libxl__device_kind_from_json(libxl_ctx *ctx, libxl__device_kind *p, const char *s)
{
    return libxl__object_from_json(ctx, "libxl__device_kind", (libxl__json_parse_callback)&libxl___device_kind_parse_json, p, s);
}

int libxl___console_backend_parse_json(libxl__gc *gc, const libxl__json_object *o, libxl__console_backend *p)
{
    int rc = 0;
    const libxl__json_object *x = o;
    {
        const char *enum_str;
        if (!libxl__json_object_is_string(x)) {
            rc = -1;
            goto out;
        }
        enum_str = libxl__json_object_get_string(x);
        rc = libxl__console_backend_from_string(enum_str, p);
        if (rc)
            goto out;
    }
    out:
    return rc;
}

int libxl__console_backend_from_json(libxl_ctx *ctx, libxl__console_backend *p, const char *s)
{
    return libxl__object_from_json(ctx, "libxl__console_backend", (libxl__json_parse_callback)&libxl___console_backend_parse_json, p, s);
}

int libxl___device_console_parse_json(libxl__gc *gc, const libxl__json_object *o, libxl__device_console *p)
{
    int rc = 0;
    const libxl__json_object *x = o;
    {
        const libxl__json_object *saved_backend_domid = x;
        x = libxl__json_map_get("backend_domid", o, JSON_INTEGER);
        if (x) {
            rc = libxl__uint32_parse_json(gc, x, &p->backend_domid);
            if (rc)
                goto out;
        }
        x = saved_backend_domid;
    }
    {
        const libxl__json_object *saved_devid = x;
        x = libxl__json_map_get("devid", o, JSON_INTEGER);
        if (x) {
            rc = libxl__int_parse_json(gc, x, &p->devid);
            if (rc)
                goto out;
        }
        x = saved_devid;
    }
    {
        const libxl__json_object *saved_consback = x;
        x = libxl__json_map_get("consback", o, JSON_STRING);
        if (x) {
            {
                const char *enum_str;
                if (!libxl__json_object_is_string(x)) {
                    rc = -1;
                    goto out;
                }
                enum_str = libxl__json_object_get_string(x);
                rc = libxl__console_backend_from_string(enum_str, &p->consback);
                if (rc)
                    goto out;
            }
        }
        x = saved_consback;
    }
    {
        const libxl__json_object *saved_output = x;
        x = libxl__json_map_get("output", o, JSON_STRING | JSON_NULL);
        if (x) {
            rc = libxl__string_parse_json(gc, x, &p->output);
            if (rc)
                goto out;
        }
        x = saved_output;
    }
    {
        const libxl__json_object *saved_name = x;
        x = libxl__json_map_get("name", o, JSON_STRING | JSON_NULL);
        if (x) {
            rc = libxl__string_parse_json(gc, x, &p->name);
            if (rc)
                goto out;
        }
        x = saved_name;
    }
    {
        const libxl__json_object *saved_connection = x;
        x = libxl__json_map_get("connection", o, JSON_STRING | JSON_NULL);
        if (x) {
            rc = libxl__string_parse_json(gc, x, &p->connection);
            if (rc)
                goto out;
        }
        x = saved_connection;
    }
    {
        const libxl__json_object *saved_path = x;
        x = libxl__json_map_get("path", o, JSON_STRING | JSON_NULL);
        if (x) {
            rc = libxl__string_parse_json(gc, x, &p->path);
            if (rc)
                goto out;
        }
        x = saved_path;
    }
    out:
    return rc;
}

int libxl__device_console_from_json(libxl_ctx *ctx, libxl__device_console *p, const char *s)
{
    libxl__device_console_init(p);
    return libxl__object_from_json(ctx, "libxl__device_console", (libxl__json_parse_callback)&libxl___device_console_parse_json, p, s);
}

int libxl___device_action_parse_json(libxl__gc *gc, const libxl__json_object *o, libxl__device_action *p)
{
    int rc = 0;
    const libxl__json_object *x = o;
    {
        const char *enum_str;
        if (!libxl__json_object_is_string(x)) {
            rc = -1;
            goto out;
        }
        enum_str = libxl__json_object_get_string(x);
        rc = libxl__device_action_from_string(enum_str, p);
        if (rc)
            goto out;
    }
    out:
    return rc;
}

int libxl__device_action_from_json(libxl_ctx *ctx, libxl__device_action *p, const char *s)
{
    return libxl__object_from_json(ctx, "libxl__device_action", (libxl__json_parse_callback)&libxl___device_action_parse_json, p, s);
}

