#ifndef __LIBXL_TYPES_INTERNAL_JSON_H
#define __LIBXL_TYPES_INTERNAL_JSON_H

/*
 * DO NOT EDIT.
 *
 * This file is autogenerated by
 * "gentypes.py libxl_types_internal.idl __libxl_types_internal.h __libxl_types_internal_private.h __libxl_types_internal_json.h __libxl_types_internal.c"
 */

_hidden yajl_gen_status libxl__qmp_message_type_gen_json(yajl_gen hand, libxl__qmp_message_type *p);
_hidden yajl_gen_status libxl__device_kind_gen_json(yajl_gen hand, libxl__device_kind *p);
_hidden yajl_gen_status libxl__console_backend_gen_json(yajl_gen hand, libxl__console_backend *p);
_hidden yajl_gen_status libxl__device_console_gen_json(yajl_gen hand, libxl__device_console *p);
_hidden yajl_gen_status libxl__device_action_gen_json(yajl_gen hand, libxl__device_action *p);

#endif /* __LIBXL_TYPES_INTERNAL_JSON_H */
