#ifndef __LIBXL_TYPES_INTERNAL_H
#define __LIBXL_TYPES_INTERNAL_H

/*
 * DO NOT EDIT.
 *
 * This file is autogenerated by
 * "gentypes.py libxl_types_internal.idl __libxl_types_internal.h __libxl_types_internal_private.h __libxl_types_internal_json.h __libxl_types_internal.c"
 */

typedef enum libxl__qmp_message_type {
    LIBXL__QMP_MESSAGE_TYPE_QMP = 1,
    LIBXL__QMP_MESSAGE_TYPE_RETURN = 2,
    LIBXL__QMP_MESSAGE_TYPE_ERROR = 3,
    LIBXL__QMP_MESSAGE_TYPE_EVENT = 4,
    LIBXL__QMP_MESSAGE_TYPE_INVALID = 5,
} libxl__qmp_message_type;
_hidden char *libxl__qmp_message_type_to_json(libxl_ctx *ctx, libxl__qmp_message_type p);
_hidden int libxl__qmp_message_type_from_json(libxl_ctx *ctx, libxl__qmp_message_type *p, const char *s);
_hidden const char *libxl__qmp_message_type_to_string(libxl__qmp_message_type p);
_hidden int libxl__qmp_message_type_from_string(const char *s, libxl__qmp_message_type *e);
_hidden extern libxl_enum_string_table libxl__qmp_message_type_string_table[];

typedef enum libxl__device_kind {
    LIBXL__DEVICE_KIND_VIF = 1,
    LIBXL__DEVICE_KIND_VBD = 2,
    LIBXL__DEVICE_KIND_QDISK = 3,
    LIBXL__DEVICE_KIND_PCI = 4,
    LIBXL__DEVICE_KIND_VFB = 5,
    LIBXL__DEVICE_KIND_VKBD = 6,
    LIBXL__DEVICE_KIND_CONSOLE = 7,
    LIBXL__DEVICE_KIND_VTPM = 8,
} libxl__device_kind;
_hidden char *libxl__device_kind_to_json(libxl_ctx *ctx, libxl__device_kind p);
_hidden int libxl__device_kind_from_json(libxl_ctx *ctx, libxl__device_kind *p, const char *s);
_hidden const char *libxl__device_kind_to_string(libxl__device_kind p);
_hidden int libxl__device_kind_from_string(const char *s, libxl__device_kind *e);
_hidden extern libxl_enum_string_table libxl__device_kind_string_table[];

typedef enum libxl__console_backend {
    LIBXL__CONSOLE_BACKEND_XENCONSOLED = 1,
    LIBXL__CONSOLE_BACKEND_IOEMU = 2,
} libxl__console_backend;
_hidden char *libxl__console_backend_to_json(libxl_ctx *ctx, libxl__console_backend p);
_hidden int libxl__console_backend_from_json(libxl_ctx *ctx, libxl__console_backend *p, const char *s);
_hidden const char *libxl__console_backend_to_string(libxl__console_backend p);
_hidden int libxl__console_backend_from_string(const char *s, libxl__console_backend *e);
_hidden extern libxl_enum_string_table libxl__console_backend_string_table[];

typedef struct libxl__device_console {
    libxl_domid backend_domid;
    int devid;
    libxl__console_backend consback;
    char * output;
    char * name;
    char * connection;
    char * path;
} libxl__device_console;
_hidden void libxl__device_console_dispose(libxl__device_console *p);
_hidden void libxl__device_console_copy(libxl_ctx *ctx, libxl__device_console *dst, libxl__device_console *src);
_hidden void libxl__device_console_init(libxl__device_console *p);
_hidden char *libxl__device_console_to_json(libxl_ctx *ctx, libxl__device_console *p);
_hidden int libxl__device_console_from_json(libxl_ctx *ctx, libxl__device_console *p, const char *s);

typedef enum libxl__device_action {
    LIBXL__DEVICE_ACTION_ADD = 1,
    LIBXL__DEVICE_ACTION_REMOVE = 2,
} libxl__device_action;
_hidden char *libxl__device_action_to_json(libxl_ctx *ctx, libxl__device_action p);
_hidden int libxl__device_action_from_json(libxl_ctx *ctx, libxl__device_action *p, const char *s);
_hidden const char *libxl__device_action_to_string(libxl__device_action p);
_hidden int libxl__device_action_from_string(const char *s, libxl__device_action *e);
_hidden extern libxl_enum_string_table libxl__device_action_string_table[];

#endif /* __LIBXL_TYPES_INTERNAL_H */
